### PR TITLE
Fixed part of issue #456

### PR DESCRIPTION
**Pull request by drewproud**
@drenfr01 this should fix issue 1 in #456 . I manually made the change in prod DB, but also updated the seed data, which we should deploy at some point in order to add the new category.

I wasn't able to figure out point 2 yet - any chance you could take a look at that? If not, I'll be online Wednesday night to check it out.

We can probably go ahead and deploy this fix as soon as you are ready.

### CODE REVIEW

**Comment by drenfr01** [comment]
@drewproud Awesome, thanks drewski! I'll deploy it right now. So was the bug that in the isRecognizedEvent function it basically always returned true because there was a "new" event to match on. 

Also, I don't quite understand the addition of Super_admin only to the adminRules checks. Is that insurance to make sure we don't auto-approve selfies ever? 

Finally, what is the point of adminRulesFalse / adminRulesTrue, or rather why are there two separate functions?

**Comment by unioncapitalboston** [comment]
Duncan - I think the answer to your question about superAdmin approval is this, but I could be confusing your question:
superAdmin approval for ALL "Community: OTHER" selfie events needs to be required because technically all the approved Points activities are listed in all the other categories. If a member feels that something they did is eligible for Points but isn't in one of the other categories (an example might be something like "Donating Blood"), they can list it and submit it in OTHER. But because it is a new type of event we have to review every OTHER submission to make sure it fits our guidelines. All other Selfie submission categories should remain as auto-approved for submissions less than 2 hours. Thanks!

**Comment by drewproud** [comment]
@drenfr01 

> So was the bug that in the isRecognizedEvent function it basically always returned true because there was a "new" event to match on.

The bug was that OTHER category didn't have any selfie rules associated with it, so it just gets auto-approved. Even if `IS_RECOGNIZED_EVENT` is false, it still met all of the other criteria.

> Also, I don't quite understand the addition of Super_admin only to the adminRules checks. Is that insurance to make sure we don't auto-approve selfies ever?

So @unioncapitalboston is spot on with his explanation there. We've never had the concept of automatic admin verification before, so I had to add a new rule to account for this.

> Oh, and I awesome the seed data change is just EBNHC - Asthma Management as an eventCategory, correct?

Yes, and adding `SUPER_ADMIN_ONLY` to that and OTHER.

**Comment by ballek** [comment]
@drewproud @drenfr01 THANKS Y'ALL

**Pull request merged**
